---
- name: Create Guacd Docker Container
  docker_container:
    name: guacd
    image: "linuxserver/guacd:{{guacd_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
  tags: 
    - guacd
    - guacamole

- import_tasks: roles/postgres/tasks/database_manager.yml
  vars:
    database_name: "{{guacamole_database}}"
    database_user: "{{guacamole_database_user}}"
    database_password: "{{guacamole_database_password}}"
  tags: guacamole

- name: Create Guacamole Docker Container
  docker_container:
    name: guacamole
    image: "guacamole/guacamole:{{guacamole_version}}"
    user: root
    pull: yes
    links:
      - guacd:guacd
      - database:postgres
    restart_policy: unless-stopped
    env:
      JAVA_OPTS: "-Dserver.use-forward-headers=true"
      GUACD_HOSTNAME: "guacd"
      POSTGRES_HOSTNAME: "database"
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: "{{guacamole_database}}"
      POSTGRES_USER: "{{guacamole_database_user}}"
      POSTGRES_PASSWORD: "{{guacamole_database_password}}"
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    labels:
      traefik.http.routers.guacamole.entrypoints: "websecure"
      traefik.http.routers.guacamole.tls: "true"
      traefik.http.routers.guacamole.rule: "Host(`guac.{{project_tld}}`)"
      traefik.http.routers.guacamole.middlewares: "default-headers@file"
      traefik.http.routers.guacamole.service: "guacamole"
      traefik.http.services.guacamole.loadbalancer.server.port: "8080"
      traefik.enable: "true"
  tags: guacamole
