---
- name: Log into Private Registry
  docker_login:
    registry: "{{registry_host}}"
    username: "{{registry_username}}"
    password: "{{registry_password}}"
    reauthorize: yes
  register: registry_state