---
- name: Create Hydra directory
  file:
    path: "{{project_directory}}/hydra"
    state: directory
    owner: "{{media_user}}"
    group: "{{media_group}}"
  tags: hydra

- name: Create Hydra Docker Container
  docker_container:
    name: hydra
    image: "linuxserver/nzbhydra2:{{hydra_version}}"
    pull: yes
    restart_policy: unless-stopped
    comparisons:
      labels: allow_more_present
      '*': strict
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
    volumes:
      - "{{project_directory}}/hydra:/config"
      - "{{media_directory}}/downloads:/downloads"
    labels:
      traefik.http.routers.hydra.entrypoints: "websecure"
      traefik.http.routers.hydra.tls: "true"
      traefik.http.routers.hydra.rule: "Host(`hydra.{{project_tld}}`)"
      traefik.http.routers.hydra.middlewares: "default-headers@file"
      traefik.http.routers.hydra.service: "hydra"
      traefik.http.services.hydra.loadbalancer.server.port: "5076"
      traefik.enable: "true"
  tags: hydra
