---
- name: Create Home Assistant Directory
  file:
    path: "{{project_directory}}/homeassistant"
    state: directory

- name: Create Home Assistant Docker Container
  docker_container:
    name: homeassistant
    image: "homeassistant/home-assistant:{{homeassistant_version}}"
    pull: yes
    restart_policy: unless-stopped
    env:
      TZ: "{{default_timezone}}"
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    volumes:
      - "{{project_directory}}/homeassistant:/config"
    labels:
      traefik.http.routers.homeassistant.entrypoints: "websecure"
      traefik.http.routers.homeassistant.tls: "true"
      traefik.http.routers.homeassistant.rule: "Host(`hass.{{project_tld}}`)"
      traefik.http.routers.homeassistant.service: "homeassistant"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
      traefik.enable: "true"
  notify: restart home assistant
