---
- name: Create Bitwarden Directory
  file:
    path: "{{project_directory}}/bitwarden"
    state: directory
    owner: "root"
    group: "root"
  tags: bitwarden

- name: Bitwarden Configuration Files
  template: 
    src: config.json.j2 
    dest: "{{project_directory}}/bitwarden/config.json"
  notify: restart bitwarden
  tags: bitwarden

- name: Create Bitwarden Docker Container
  docker_container:
    name: bitwarden
    image: "{{registry_host}}/{{registry_username}}/docker-bitwarden:{{bitwarden_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: "{{bitwarden_admin_token}}"
      SMTP_HOST: "{{email_host}}"
      SMTP_FROM: "{{email_user}}"
      SMTP_PORT: "{{email_port}}"
      SMTP_SSL: "true"
      SMTP_USERNAME: "{{email_user}}"
      SMTP_PASSWORD: "{{email_password}}"
    volumes:
      - "{{project_directory}}/bitwarden:/data"
    labels:
      traefik.http.routers.bitwarden.entrypoints: "websecure"
      traefik.http.routers.bitwarden.tls: "true"
      traefik.http.routers.bitwarden.rule: "Host(`vault.{{project_tld}}`)"
      traefik.http.routers.bitwarden.service: "bitwarden"
      traefik.http.services.bitwarden.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: bitwarden
