---
- name: Create Wallabag Image volume
  docker_volume:
    name: wallabag_images
    state: present
  tags: wallabag

- import_tasks: roles/postgres/tasks/database_manager.yml
  vars:
    database_name: "{{wallabag_database}}"
    database_user: "{{wallabag_database_user}}"
    database_password: "{{wallabag_database_password}}"
  tags: wallabag

- name: Create Wallabag Docker Container
  docker_container:
    name: wallabag
    image: "wallabag/wallabag:{{wallabag_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      POSTGRES_USER: "{{wallabag_database_user}}"
      POSTGRES_PASSWORD: "{{wallabag_database_password}}"
      SYMFONY__ENV__DATABASE_DRIVER_CLASS: "{{wallabag_database_class}}"
      POSTGRES_DB: "{{wallabag_database}}"
      SYMFONY__ENV__DATABASE_DRIVER: "pdo_pgsql"
      SYMFONY__ENV__DATABASE_HOST: "database"
      SYMFONY__ENV__DATABASE_PORT: "5432"
      SYMFONY__ENV__DATABASE_NAME: "{{wallabag_database}}"
      SYMFONY__ENV__DATABASE_USER: "{{wallabag_database_user}}"
      SYMFONY__ENV__DATABASE_PASSWORD: "{{wallabag_database_password}}"
      SYMFONY__ENV__MAILER_HOST: "{{email_host}}"
      SYMFONY__ENV__MAILER_USER: "{{email_user}}"
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
      SYMFONY__ENV__MAILER_PASSWORD: "{{email_password}}"
      SYMFONY__ENV__FROM_EMAIL: "{{email_user}}"
      SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.{{project_tld}}"
      SYMFONY__ENV__REDIS_SCHEME: "tcp"
      SYMFONY__ENV__REDIS_HOST: "{{redis_host}}"
      SYMFONY__ENV__REDIS_PORT: "{{redis_port}}"
    volumes:
      - wallabag_images:/var/www/wallabag/web/assets/images
    labels:
      traefik.http.routers.wallabag.entrypoints: "websecure"
      traefik.http.routers.wallabag.tls: "true"
      traefik.http.routers.wallabag.rule: "Host(`wallabag.{{project_tld}}`)"
      traefik.http.routers.wallabag.middlewares: "default-headers@file"
      traefik.http.routers.wallabag.service: "wallabag"
      traefik.http.services.wallabag.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: wallabag
